<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_samePswdpls</name>
   <tag></tag>
   <elementGuidId>c36dc64a-47a2-4b28-b8fc-6101f48cf628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]/div/div[2]/div/div/div/div/form/div/div[3]/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0717dd86-6d3c-4674-9b26-c6b1d91fc341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-form-item-feedback__line</value>
      <webElementGuid>1c3428cf-fe31-4533-a32c-1f105f810fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>請輸入相同密碼</value>
      <webElementGuid>a8f1d8c1-b8d0-44a9-9baa-50aafae43af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;justify-center my-14 mx-auto min-h-3/5 w-2/3&quot;]/div[@class=&quot;n-card n-card--bordered&quot;]/div[@class=&quot;n-card__content&quot;]/form[@class=&quot;n-form&quot;]/div[@class=&quot;n-space&quot;]/div[3]/div[@class=&quot;n-form-item n-form-item--small-size n-form-item--left-labelled&quot;]/div[@class=&quot;n-form-item-feedback-wrapper&quot;]/div[@class=&quot;n-form-item-feedback n-form-item-feedback--error&quot;]/div[@class=&quot;n-form-item-feedback__line&quot;]</value>
      <webElementGuid>f06bdd8c-6ec7-4776-b2c0-0a5e17161e61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div[2]/div/div/div/div/form/div/div[3]/div/div[2]/div/div</value>
      <webElementGuid>5aba1a13-117e-46af-ab6f-52da1ea26e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='密碼確認'])[1]/following::div[11]</value>
      <webElementGuid>9ac862eb-c7a9-419b-82ea-4c84ac32a970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='姓名'])[1]/preceding::div[1]</value>
      <webElementGuid>448e5a5f-282e-4cdd-a9ee-d2adbfa52658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='請輸入相同密碼']/parent::*</value>
      <webElementGuid>13b1fa03-d9f1-4d56-90f5-a028923228b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div</value>
      <webElementGuid>5d7e1cf0-21bf-483d-82d9-43cc43d013eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '請輸入相同密碼' or . = '請輸入相同密碼')]</value>
      <webElementGuid>606dad03-34c3-46ad-8cb8-65c90c0c57e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
