<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__confirmPswd</name>
   <tag></tag>
   <elementGuidId>e59479ea-316b-4e56-9b46-ddb18358b937</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-input.n-input--resizable.n-input--focus.n-input--stateful > div.n-input-wrapper > div.n-input__input > input.n-input__input-el</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='password'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e3d7203-c512-409e-9d65-284be134259d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3395a0d1-ef25-472e-98e2-ea98b6d6f9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-input__input-el</value>
      <webElementGuid>e0cd8c7a-545f-431e-bd6d-838f28efbf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>請輸入</value>
      <webElementGuid>13c5e038-e868-4fb7-b082-26362c30cf8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>20d354e8-b682-484e-960d-28ad8681bc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;justify-center my-14 mx-auto min-h-3/5 w-1/3 &lt;lg:w-11/12&quot;]/div[@class=&quot;n-card n-card--bordered&quot;]/div[@class=&quot;n-card__content&quot;]/form[@class=&quot;n-form&quot;]/div[@class=&quot;n-form-item __form-item-ml n-form-item--medium-size n-form-item--left-labelled n-form-item--auto-label-width&quot;]/div[@class=&quot;n-form-item-blank&quot;]/div[@class=&quot;n-input n-input--resizable n-input--focus n-input--stateful&quot;]/div[@class=&quot;n-input-wrapper&quot;]/div[@class=&quot;n-input__input&quot;]/input[@class=&quot;n-input__input-el&quot;]</value>
      <webElementGuid>9497a831-3f1b-45ad-a562-17494f945374</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='password'])[3]</value>
      <webElementGuid>34057868-0a95-4ea8-84a8-30ce1a543ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div/div/div/div/form/div[3]/div/div/div/div/input</value>
      <webElementGuid>a2000f1a-032a-4f47-a49e-50f20aef5369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/input</value>
      <webElementGuid>68cdad31-0a07-47c1-8677-d650fc5b5a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = '請輸入']</value>
      <webElementGuid>ff561503-3829-4b90-92e4-e779c65b1c08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
