<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_chooseReviewer_clear</name>
   <tag></tag>
   <elementGuidId>8854b7e3-4d94-4f85-99d1-f0f1c7e608c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-transfer-list.n-transfer-list--target > div.n-transfer-list-header > button.n-button.n-button--default-type.n-button--tiny-type.n-transfer-list-header__button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b85b054-0dfc-42db-95ea-0e60daf5c314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-button n-button--default-type n-button--tiny-type n-transfer-list-header__button</value>
      <webElementGuid>a6961a79-508c-49b6-8079-d9fe6b10f573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e996db3d-3d7e-46e5-af69-83ea19f30b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>806d2d19-8f70-4c5b-8925-02c6457adee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>清除</value>
      <webElementGuid>1d1b8e5c-f6e0-49c4-a83c-ddc075701086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;n-modal-container&quot;]/div[@class=&quot;n-modal-body-wrapper&quot;]/div[@class=&quot;n-scrollbar&quot;]/div[@class=&quot;n-scrollbar-container&quot;]/div[@class=&quot;n-scrollbar-content n-modal-scroll-content&quot;]/div[@class=&quot;n-card n-card--bordered min-w-1/3 w-screen-lg &lt;lg:w-11/12 n-modal&quot;]/div[@class=&quot;n-card__content&quot;]/div[@class=&quot;n-collapse&quot;]/div[@class=&quot;n-collapse&quot;]/div[@class=&quot;n-collapse-item n-collapse-item--left-arrow-placement n-collapse-item--active&quot;]/div[@class=&quot;n-collapse-item__content-wrapper&quot;]/div[@class=&quot;n-collapse-item__content-inner&quot;]/div[@class=&quot;n-transfer&quot;]/div[@class=&quot;n-transfer-list n-transfer-list--target&quot;]/div[@class=&quot;n-transfer-list-header&quot;]/button[@class=&quot;n-button n-button--default-type n-button--tiny-type n-transfer-list-header__button&quot;]</value>
      <webElementGuid>f8c72072-ab58-4e45-b471-5b84d7a006dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>00c32d27-9420-4899-82f6-4a071304ad05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testReviewer03'])[1]/following::button[1]</value>
      <webElementGuid>059b8a50-d6f3-455a-b7ea-6d5f76407974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testReviewer02'])[1]/following::button[1]</value>
      <webElementGuid>03c4da71-0d94-4df0-a7d8-0a6cb9c4e760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='已選 3 項'])[1]/preceding::button[1]</value>
      <webElementGuid>06922382-8d72-48bb-a1b5-5608493c074f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>b4f85cfa-efdd-460b-91e1-9bc429609a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '清除' or . = '清除')]</value>
      <webElementGuid>ad4d3d39-2e66-456b-9ea7-1423cf1140f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
