<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_confirmCreate</name>
   <tag></tag>
   <elementGuidId>15092a1b-eb35-4998-b4b7-5fc6ce864532</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[14]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.n-button.n-button--primary-type.n-button--small-type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3bb1712b-45d8-4db6-8423-4c66497e95f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-button n-button--primary-type n-button--small-type</value>
      <webElementGuid>bd645163-2623-4ace-8939-3c7d8dc198d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e7fc1a09-05f2-44ba-9123-fa02c6c8200c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18543726-5ac2-4d6e-ba40-27d5818ed34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>確認</value>
      <webElementGuid>35a0d34e-20f0-4454-90ef-00199cf4cdc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;n-modal-container&quot;]/div[@class=&quot;n-modal-body-wrapper&quot;]/div[@class=&quot;n-scrollbar&quot;]/div[@class=&quot;n-scrollbar-container&quot;]/div[@class=&quot;n-scrollbar-content n-modal-scroll-content&quot;]/div[@class=&quot;n-card n-card--bordered min-w-1/3 w-screen-lg &lt;lg:w-11/12 n-modal&quot;]/div[@class=&quot;v-binder-follower-container&quot;]/div[@class=&quot;v-binder-follower-content&quot;]/div[@class=&quot;n-popover n-popover-shared n-popconfirm n-popover-shared--show-arrow&quot;]/div[@class=&quot;n-popover__content&quot;]/div[@class=&quot;n-popconfirm__panel&quot;]/div[@class=&quot;n-popconfirm__action&quot;]/button[@class=&quot;n-button n-button--primary-type n-button--small-type&quot;]</value>
      <webElementGuid>3393e934-25f7-4ce5-ac85-b4be5210eb81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[14]</value>
      <webElementGuid>27b32b11-9d47-4c56-ae28-39f7d2ec717f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='取消'])[1]/following::button[1]</value>
      <webElementGuid>7ed4675d-8776-4c37-860c-38ed61129a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>9a4d2f92-0075-4f26-9d6e-bede839bdef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '確認' or . = '確認')]</value>
      <webElementGuid>82d6afce-efec-4d8b-8e2b-2906977efb9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
