<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__checkbox_Must</name>
   <tag></tag>
   <elementGuidId>7d2f4375-15dc-4040-869f-9c38258d8ddd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-checkbox-box__border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div/div[3]/div/div/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'n-checkbox-box__border']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5188b8d0-6f98-4b1a-a814-09e088060aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-checkbox-box__border</value>
      <webElementGuid>7c33674b-bfd5-482a-ad48-50ad2b2393bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;n-modal-container&quot;]/div[@class=&quot;n-modal-body-wrapper&quot;]/div[@class=&quot;n-scrollbar&quot;]/div[@class=&quot;n-scrollbar-container&quot;]/div[@class=&quot;n-scrollbar-content n-modal-scroll-content&quot;]/div[@class=&quot;n-card n-card--bordered min-w-1/3 w-screen-lg &lt;lg:w-11/12 n-modal&quot;]/div[@class=&quot;n-card__content&quot;]/div[@class=&quot;n-collapse&quot;]/div[@class=&quot;n-collapse-item n-collapse-item--left-arrow-placement n-collapse-item--active&quot;]/div[@class=&quot;n-collapse-item__content-wrapper&quot;]/div[@class=&quot;n-collapse-item__content-inner&quot;]/div[@class=&quot;n-dynamic-input&quot;]/div[@class=&quot;n-dynamic-input-item&quot;]/div[@class=&quot;n-space&quot;]/div[3]/div[@class=&quot;n-space&quot;]/div[1]/div[@class=&quot;n-checkbox&quot;]/div[@class=&quot;n-checkbox-box-wrapper&quot;]/div[@class=&quot;n-checkbox-box&quot;]/div[@class=&quot;n-checkbox-box__border&quot;]</value>
      <webElementGuid>ae8b3255-f01e-4156-a9b1-44a06a659e3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/div/div/div/div/div/div[2]</value>
      <webElementGuid>3b084ff7-6124-44d8-9867-e0eabca728b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
