<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_enterName</name>
   <tag></tag>
   <elementGuidId>7224d302-4d53-4a20-aa58-24e5d7524a0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='newProgram']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#newProgram > div.n-card__content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eca5093a-86d4-4c98-a4b4-8fa7ee71d5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-card__content</value>
      <webElementGuid>934c00f5-2eb2-4c36-bb64-4fc8a89a71d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ef6772d9-1e45-414f-a2f0-826024db6bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>輸入計畫名稱新增</value>
      <webElementGuid>e099ea60-6c2f-4362-a50f-08e036b61aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newProgram&quot;)/div[@class=&quot;n-card__content&quot;]</value>
      <webElementGuid>8f0f473d-942f-493d-bb24-8db8324ac98f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newProgram']/div</value>
      <webElementGuid>633c2407-2844-412f-a6fb-3720bbf1f869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'newProgram', '&quot;', ')/div[@class=', '&quot;', 'n-card__content', '&quot;', ']')])[1]/following::div[9]</value>
      <webElementGuid>98e9bb8e-e6f6-41e9-a834-c28c22ec5a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[10]</value>
      <webElementGuid>a5ce6b80-41d7-455f-9ace-9765982916c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[3]/div</value>
      <webElementGuid>3d7efbe3-8491-44d5-b9b6-c7361007918b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '輸入計畫名稱新增' or . = '輸入計畫名稱新增')]</value>
      <webElementGuid>9d8372e6-d432-416e-b4e7-229b3c7971e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
