<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_upload</name>
   <tag></tag>
   <elementGuidId>75f3a0c8-c191-4f0b-bef6-542e1aa3bb92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-upload-trigger.n-upload-trigger--disabled > button.n-button.n-button--default-type.n-button--medium-type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3af26649-9bc8-4fd8-8a6c-d9c30bcc115d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-button n-button--default-type n-button--medium-type</value>
      <webElementGuid>090bf3f9-d476-402f-952a-79d9c493e48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eb551f19-f0c0-4a60-9d6a-80237d80927f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77fda4dc-23e8-4d35-be6b-f784385ca92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>上傳</value>
      <webElementGuid>2150bc48-cc35-4565-8911-956c0695f6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;justify-center my-14 mx-auto min-h-3/5 w-1/3&quot;]/div[@class=&quot;n-card n-card--bordered&quot;]/div[@class=&quot;n-card__content&quot;]/form[@class=&quot;n-form&quot;]/div[@class=&quot;n-form-item n-form-item--medium-size n-form-item--top-labelled&quot;]/div[@class=&quot;n-form-item-blank&quot;]/div[@class=&quot;n-upload&quot;]/div[@class=&quot;n-upload-trigger n-upload-trigger--disabled&quot;]/button[@class=&quot;n-button n-button--default-type n-button--medium-type&quot;]</value>
      <webElementGuid>07197102-ad83-4f5b-9404-9b774691bc2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>9187bfe9-8389-40a8-9824-0208f872dc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div[2]/div/div/div/div/form/div[8]/div/div/div/button</value>
      <webElementGuid>b7cd9b5e-a5d9-4393-bfb6-f12bae18470e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='score'])[1]/following::button[1]</value>
      <webElementGuid>87575cb9-5663-4374-ae9c-9b04cbd8d6e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FinalProject.pdf'])[1]/preceding::button[1]</value>
      <webElementGuid>a04a0f14-8291-439e-98c1-de37b4e1cb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/button</value>
      <webElementGuid>082afa57-10f9-4cbf-8ecb-08d466591920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '上傳' or . = '上傳')]</value>
      <webElementGuid>abc6b578-0fef-429a-be2a-9b82978a44d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
