<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_File</name>
   <tag></tag>
   <elementGuidId>20398a29-efb0-4077-9f39-757dc08980bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n-upload-file.n-upload-file--info-status.n-upload-file--text-type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]/div/div[2]/div/div/div/div/form/div[8]/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a9d4d46-e65d-4d96-87e9-878d5673845e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n-upload-file n-upload-file--info-status n-upload-file--text-type</value>
      <webElementGuid>9274d142-8cab-4af4-b851-eda32ed4f6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FinalProject.pdf</value>
      <webElementGuid>e5ea7855-942a-4fe7-b56e-195d50eafd5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-config-provider&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;n-layout n-layout--absolute-positioned&quot;]/div[@class=&quot;n-layout-scroll-container&quot;]/div[@class=&quot;justify-center my-14 mx-auto min-h-3/5 w-1/3&quot;]/div[@class=&quot;n-card n-card--bordered&quot;]/div[@class=&quot;n-card__content&quot;]/form[@class=&quot;n-form&quot;]/div[@class=&quot;n-form-item n-form-item--medium-size n-form-item--top-labelled&quot;]/div[@class=&quot;n-form-item-blank&quot;]/div[@class=&quot;n-upload&quot;]/div[@class=&quot;n-upload-file-list&quot;]/div[@class=&quot;n-upload-file n-upload-file--info-status n-upload-file--text-type&quot;]</value>
      <webElementGuid>1c126d16-dc62-4ebe-977f-f54fbbdd62bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div/div[2]/div/div/div/div/form/div[8]/div/div/div[2]/div</value>
      <webElementGuid>e1edaf11-32d3-4f9b-a5da-e6cf95c18ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='上傳'])[1]/following::div[5]</value>
      <webElementGuid>355dfe30-d096-4c34-a857-ce8d9d2d43f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='file2'])[1]/preceding::div[7]</value>
      <webElementGuid>69c3f2a0-e77c-4bf1-8663-f18033e266e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div</value>
      <webElementGuid>7fcfd7ac-69d6-42ad-8705-ac4c45d3ade5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'FinalProject.pdf' or . = 'FinalProject.pdf')]</value>
      <webElementGuid>a6de6d1b-5f00-4f2a-b1e3-1bb4b402fb5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
